services:
  - type: web
    name: flask-portfolio
    runtime: python
    buildCommand: ""
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
